#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"
AUTH_DIR="${APP_DATA_DIR}/auth"

# create auth dir
[ ! -d "${AUTH_DIR}" ] && mkdir -p "${AUTH_DIR}"

# ensure there's a htpasswd file there, and create one with default creds if not
[ ! -f "${AUTH_DIR}/htpasswd" ] && \
  /usr/bin/docker run --rm marcnuri/htpasswd -Bbn "admin" "admin" > "${AUTH_DIR}/htpasswd"
